import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

import localFont from "next/font/local"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const myCustomFont = localFont({
  src: './fonts/Panchang-Bold.woff2', // Path to your font file
  variable: '--font-custom', // Define a CSS variable
  display: 'swap',
});

const myCustomFontSecond = localFont({
  src: './fonts/CabinetGrotesk-Regular.woff2', // Path to your font file
  variable: '--font-customsecond', // Define a CSS variable
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Aashish Raja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myCustomFont.variable} ${myCustomFontSecond.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
